apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo
labels:
  app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: odoo
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432
              name: postgres

          envFrom:
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          # ✅ IMPORTANT RESOURCE LIMITS
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "5Gi"

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - odoo
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - odoo
            initialDelaySeconds: 5
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
